// <auto-generated />
namespace BacklogManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingrankfieldstoPBI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingrankfieldstoPBI));
        
        string IMigrationMetadata.Id
        {
            get { return "201503152158167_Adding rank fields to PBI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
